[package]
name = "git-pr-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
subprocess = { version = "0.2.8" }
recap ={}
serde ={}
[dev-dependencies]
pretty_assertions = "1"
