newline_style            = "Unix"
use_field_init_shorthand = true
use_try_shorthand        = true

# Unstable features below
version                     = "Two"
unstable_features           = true
comment_width               = 100
error_on_line_overflow      = true
format_code_in_doc_comments = true
format_macro_bodies         = true
format_macro_matchers       = true
format_strings              = true
imports_granularity         = "Crate"
reorder_modules             = true
group_imports               = "StdExternalCrate"
normalize_doc_attributes    = true
wrap_comments               = true
trailing_semicolon          = false
condense_wildcard_suffixes  = true
